version: "3"

tasks:
  generatetus:
    aliases:
      - gen-tus
    desc: "Generate code from tus proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/tus/ --grpc_python_out=./gen/tus/ proto/tus.proto

  generatemobilebank:
    aliases:
      - gen-mob
      - gen-mbank
    desc: "Generate code from mobile bank proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/mobile_bank/ --grpc_python_out=./gen/mobile_bank/ proto/mobile_bank.proto

  generatecards:
    aliases:
      - gen-cards
    desc: "Generate code from cards proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/cards/ --grpc_python_out=./gen/cards/ proto/cards.proto

  generatecardprices:
    aliases:
      - gen-prices
      - gen-cprices
    desc: "Generate code from card prices proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/card_prices/ --grpc_python_out=./gen/card_prices/ proto/card_prices.proto
